export const GET_GETDATA_REQUEST="GET_GETDATA_REQUEST"
export const GET_GETDATA_SUCCESS="GET_GETDATA_SUCCESS"
export const GET_GETDATA_FAILURE="GET_GETDATA_FAILURE"

export const GET_GETSINGLEDATA_REQUEST="GET_GETSINGLEDATA_REQUEST"
export const GET_GETSINGLEDATA_SUCCESS="GET_GETSINGLEDATA_SUCCESS"
export const GET_GETSINGLEDATA_FAILURE="GET_GETSINGLEDATA_FAILURE"
